n1 = int(input("n1: "))
n2 = int(input("n2: "))
print('{}  +  {} = {}'.format(n1, n2, n1 + n2))
print('{}  -  {} = {}'.format(n1, n2, n1 - n2))
print('{}  *  {} = {}'.format(n1, n2, n1 * n2))
print('{}  /  {} = {}'.format(n1, n2, n1 / n2))
print('{} **  {} = {}'.format(n1, n2, n1 ** n2))
print('{} //  {} = {}'.format(n1, n2, n1 // n2))